[build]
  command = "npm run netlify-build"
  publish = "client/build"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"

[functions]
  external_node_modules = ["google-auth-library", "axios", "@google-analytics/data"]
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200