[build]
  command = "npm run netlify-build"
  publish = "client/build"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"

[functions]
  external_node_modules = ["google-auth-library", "axios"]
  node_bundler = "esbuild"
  
[[functions]]
  function = "performance"
  [functions.schedule]
    timeout = "60s"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200